"""panda-gym robot + envs for the Franka Panda fitted with the force gripper.

Uses panda_with_force_gripper.urdf (generated by scripts/make_panda_with_gripper.py;
re-run that script if it doesn't exist yet). The combined model keeps the same
joint layout as panda-gym's stock Panda: arm joints 0-6, finger joints 9-10,
end-effector frame at link 11 -- so this class mirrors panda_gym's Panda with
only the finger kinematics changed:

  - stock Franka fingers move OUTWARD from the hand center, width = q1 + q2
  - this gripper's sliders move each finger INWARD from its end of the rail,
    fingers meet when q1 + q2 = SPAN, so width = SPAN - (q1 + q2)

Example:

    from panda_force_gripper import PandaForceGripperPickAndPlaceEnv
    env = PandaForceGripperPickAndPlaceEnv(render_mode="human")
"""

import os
from typing import Optional

import numpy as np
from gymnasium import spaces

from panda_gym.envs.core import PyBulletRobot, RobotTaskEnv
from panda_gym.envs.tasks.pick_and_place import PickAndPlace
from panda_gym.envs.tasks.reach import Reach
from panda_gym.pybullet import PyBullet

HERE = os.path.dirname(os.path.abspath(__file__))
URDF_PATH = os.path.join(HERE, "panda_with_force_gripper.urdf")

SPAN = 0.0992  # full travel of each finger slider; fingers touch at q1+q2=SPAN


class PandaForceGripper(PyBulletRobot):
    """Franka Panda arm with the force-control gripper mounted on the flange."""

    def __init__(
        self,
        sim: PyBullet,
        block_gripper: bool = False,
        base_position: Optional[np.ndarray] = None,
        control_type: str = "ee",
    ) -> None:
        base_position = base_position if base_position is not None else np.zeros(3)
        self.block_gripper = block_gripper
        self.control_type = control_type
        n_action = 3 if self.control_type == "ee" else 7
        n_action += 0 if self.block_gripper else 1
        action_space = spaces.Box(-1.0, 1.0, shape=(n_action,), dtype=np.float32)
        super().__init__(
            sim,
            body_name="panda_force_gripper",
            file_name=URDF_PATH,
            base_position=base_position,
            action_space=action_space,
            joint_indices=np.array([0, 1, 2, 3, 4, 5, 6, 9, 10]),
            joint_forces=np.array([87.0, 87.0, 87.0, 87.0, 12.0, 120.0, 120.0, 50.0, 50.0]),
        )

        self.fingers_indices = np.array([9, 10])
        # arm neutral pose as stock Panda; fingers at 0 = fully open
        self.neutral_joint_values = np.array([0.00, 0.41, 0.00, -1.85, 0.00, 2.26, 0.79, 0.00, 0.00])
        self.ee_link = 11  # grasp_target frame at the pinch center
        for idx in self.fingers_indices:
            self.sim.set_lateral_friction(self.body_name, idx, lateral_friction=1.0)
            self.sim.set_spinning_friction(self.body_name, idx, spinning_friction=0.001)

    # ------------------------------------------------------------- actions
    def set_action(self, action: np.ndarray) -> None:
        action = np.clip(action.copy(), self.action_space.low, self.action_space.high)
        if self.control_type == "ee":
            target_arm_angles = self.ee_displacement_to_target_arm_angles(action[:3])
        else:
            target_arm_angles = self.arm_joint_ctrl_to_target_arm_angles(action[:7])

        if self.block_gripper:
            target_width = 0.0
        else:
            target_width = self.get_fingers_width() + action[-1] * 0.2
        target_width = float(np.clip(target_width, 0.0, SPAN))

        # symmetric close: each slider travels the same distance from its end
        finger_q = (SPAN - target_width) / 2
        target_angles = np.concatenate((target_arm_angles, [finger_q, finger_q]))
        self.control_joints(target_angles=target_angles)

    def ee_displacement_to_target_arm_angles(self, ee_displacement: np.ndarray) -> np.ndarray:
        ee_displacement = ee_displacement[:3] * 0.05
        target_ee_position = self.get_ee_position() + ee_displacement
        target_ee_position[2] = np.max((0, target_ee_position[2]))
        target_arm_angles = self.inverse_kinematics(
            link=self.ee_link, position=target_ee_position, orientation=np.array([1.0, 0.0, 0.0, 0.0])
        )
        return target_arm_angles[:7]

    def arm_joint_ctrl_to_target_arm_angles(self, arm_joint_ctrl: np.ndarray) -> np.ndarray:
        arm_joint_ctrl = arm_joint_ctrl * 0.05
        current = np.array([self.get_joint_angle(joint=i) for i in range(7)])
        return current + arm_joint_ctrl

    # ------------------------------------------------------------- state
    def get_obs(self) -> np.ndarray:
        ee_position = np.array(self.get_ee_position())
        ee_velocity = np.array(self.get_ee_velocity())
        if not self.block_gripper:
            return np.concatenate((ee_position, ee_velocity, [self.get_fingers_width()]))
        return np.concatenate((ee_position, ee_velocity))

    def reset(self) -> None:
        self.set_joint_neutral()

    def set_joint_neutral(self) -> None:
        self.set_joint_angles(self.neutral_joint_values)

    def get_fingers_width(self) -> float:
        q1 = self.sim.get_joint_angle(self.body_name, self.fingers_indices[0])
        q2 = self.sim.get_joint_angle(self.body_name, self.fingers_indices[1])
        return SPAN - (q1 + q2)

    def get_ee_position(self) -> np.ndarray:
        return self.get_link_position(self.ee_link)

    def get_ee_velocity(self) -> np.ndarray:
        return self.get_link_velocity(self.ee_link)


# ------------------------------------------------------------------ envs
class _ForceGripperTaskEnv(RobotTaskEnv):
    TASK_CLS = None
    BLOCK_GRIPPER = False

    def __init__(
        self,
        render_mode: str = "rgb_array",
        reward_type: str = "sparse",
        control_type: str = "ee",
        renderer: str = "Tiny",
        render_width: int = 720,
        render_height: int = 480,
        render_target_position: Optional[np.ndarray] = None,
        render_distance: float = 1.4,
        render_yaw: float = 45,
        render_pitch: float = -30,
        render_roll: float = 0,
    ) -> None:
        sim = PyBullet(render_mode=render_mode, renderer=renderer)
        robot = PandaForceGripper(
            sim,
            block_gripper=self.BLOCK_GRIPPER,
            base_position=np.array([-0.6, 0.0, 0.0]),
            control_type=control_type,
        )
        task = self.TASK_CLS(sim, reward_type=reward_type) if self.TASK_CLS is not Reach else Reach(
            sim, reward_type=reward_type, get_ee_position=robot.get_ee_position
        )
        super().__init__(
            robot,
            task,
            render_width=render_width,
            render_height=render_height,
            render_target_position=render_target_position,
            render_distance=render_distance,
            render_yaw=render_yaw,
            render_pitch=render_pitch,
            render_roll=render_roll,
        )


class PandaForceGripperReachEnv(_ForceGripperTaskEnv):
    TASK_CLS = Reach
    BLOCK_GRIPPER = True


class PandaForceGripperPickAndPlaceEnv(_ForceGripperTaskEnv):
    TASK_CLS = PickAndPlace
